CREATE TABLE IF NOT EXISTS public.ppid_permohonan (
    id bigint generated by default as identity primary key,
    no_urut integer,
    nama_lengkap text not null,
    no_identitas text not null,
    no_wa text not null,
    instansi text,
    pekerjaan text,
    alamat text,
    rincian_informasi text not null,
    tujuan_penggunaan text not null,
    cara_memperoleh text,
    cara_salinan text,
    waktu_masuk timestamp with time zone default timezone('utc'::text, now()),
    waktu_selesai timestamp with time zone,
    status text default 'menunggu'::text
);

ALTER TABLE public.ppid_permohonan ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_all_ppid" ON public.ppid_permohonan FOR ALL USING (true);
